[package]
name = "trader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bdk = "0.29.0"
clap = "4.5.4"
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
serde = "1.0.203"
